spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelesLuna
spring.datasource.username=${DB_USERNAME:usuario_ejemplo}
spring.datasource.password=${DB_PASSWORD:}

server.port=8082